### ISSUE TITLE
deprecated packages [sourcemap-codec@1.4.8, w3c-hr-time@1.0.2]

### ISSUE THREAD

**Issue by lihe6666** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#11]
<img width="1137" alt="image" src="https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/assets/2598007/d32ddc16-8464-4a1f-9a9b-4236b94bcb87">

我想请教一下，这个包怎么找到它。是那个包带着这个依赖，并且没有更新到  @jridgewell/sourcemap-codec, 我想知道用什么命令直接找到它

**Comment by sonofmagic** [comment]
这个一般是要在 lock 文件里去找到对应的依赖的，看了一下这个似乎是 magic-string@^0.25.7 这个版本带的

<img width="886" alt="image" src="https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/assets/15621541/d9ba22ea-8dba-4f3a-b4e1-e43d9900fba2">

**Comment by lihe6666** [comment]
OK， 原来是这样啊，感谢你的解答，我解决困扰我很久的问题了，赞👍
