### ISSUE TITLE
编译成小程序后webview标签消失了？

### ISSUE THREAD

**Issue by zz201276** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#12]
`<template>
    <div class='page'>
        <web-view :webview-styles="color" src="https://h5.eventnet.cn/html/xxx.html?v=1.11"></web-view>
    </div>
</template>`
编译小程序后webview标签消失了，没弄明白是什么原因。还有就是pnpm可以用了。

**Comment by sonofmagic** [comment]
我试了一下在模板里面直接加 `<web-view src="https://h5.eventnet.cn/html/xxx.html?v=1.11"></web-view>` 并没有消失呢。

你可以看一下你 `dist` 里 `wxml` 结果，看看是不是有 `web-view` 相关的结果，我的结果如下：

![WX20230828-131833@2x](https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/assets/15621541/41bd111b-0472-4cbf-a364-de838c3b3b22)

**Comment by zz201276** [comment]
`
<text>pages/Privacy/Privacy.wxml</text>`
编译完只有这么一句代码

**Comment by zz201276** [comment]
`<script lang="ts" setup>

const color = ref('#fafafa')
</script>
<template>
    <div class='page'>
        <web-view :webview-styles="color" src="https://h5.eventnet.cn/html/xxx.html?v=1.11"></web-view>
    </div>
</template>
<style></style>`
这是完整的页面代码

**Comment by zz201276** [comment]
`<script lang="ts" setup>

const color = ref('#fafafa')
</script>
<template>
    <div class='page'>
        <web-view :webview-styles="color" src="https://h5.eventnet.cn/html/xxx.html?v=1.11"></web-view>
    </div>
</template>
<style></style>`
这是完整的页面代码

**Comment by zz201276** [comment]
![image](https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/assets/50104871/5cc38265-d705-4bf2-a37f-105cd874264c)
这是完整的代码

**Comment by zz201276** [comment]
找到问题了，目录错了，感谢回答
