### ISSUE TITLE
请教uni模版中如何配置customAttributes？

### ISSUE THREAD

**Issue by hogking** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#14]
作者大大好，我想使用比如group-hover-class属性，参考了这个 https://github.com/sonofmagic/weapp-native-mina-tailwindcss-template/issues/3链接内的配置，

```
export default defineConfig({
  // uvtw 一定要放在 uni 后面
  plugins: [
    uni(),
    uvtw({
      customAttributes: {
        '*': ['group-hover-class']
      },
      disabled: WeappTailwindcssDisabled
    }),
...
```
但似乎没有生效
```
<view class="flex-1 group" group-hover-class="!bg-indigo-500 !text-red">
...
</view>
```
请问是哪里搞错了吗？

**Comment by sonofmagic** [comment]
没有搞错，就是这样配置的，我在我这个项目里测试了一下你这样的配置:

转化前的 `vue` 模板:
```html
    <view
      class="w-0.5 group"
      hover-class="!bg-indigo-500 !text-red"
      group-hover-class="!bg-indigo-500 !text-red"
      xxxxx="!bg-indigo-500 !text-red"
      data-xxx="!bg-indigo-500 !text-red">
      ...
    </view>
```

在`dist/dev/mp-weixin` 最终生成的 `wxml` 里，这段转化成了:

```html
  <view class="w-0d5 group" 
      hover-class="ibg-indigo-500 itext-red" 
      group-hover-class="ibg-indigo-500 itext-red" 
      xxxxx="!bg-indigo-500 !text-red" 
      data-xxx="!bg-indigo-500 !text-red">
    ...
  </view>
```

可以看到 `group-hover-class` 属性的值被正确的转义了，但是当我用微信开发者工具打开之后却发现变成了这样:
![image](https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/assets/15621541/8cd77e5f-a78f-479b-869c-ca25fc138982)

可以看到图里的 `group-hover-class` 和 `xxxxx` 属性直接消失了，但是 `wxml` 是有的，所以我想你这个问题可能是这个问题导致的。

你可以也去看看你 `dist` 里的 `wxml` 产物，看看结果是不是和我一样，配置 `customAttributes` 后，转义是对的，但是微信开发者工具直接认为它是非法属性，把它去掉了。

**Comment by hogking** [comment]
你好，确实是有的。这是否意味着无法在小程序中使用这个tailwindcss内置属性？

**Comment by hogking** [comment]
菜鸡表示，其实是想使用tailwindcss里的group-hover:xxxx

**Comment by sonofmagic** [comment]
目前看来的确是这样，因为 `view` 的按下去的样式类必须要用 `hover-class `这个字段，`WXSS` 里的 `:hover` 伪类都是无效的。

我试了一下， group + 其他的方式，比如:

```html
<div class="group is-published">
  <div class="hidden group-[.is-published]:block">
    Published
  </div>
</div>
```
倒是在小程序里生效的，还是 hover 这个情况比较特殊。

> 这部分用法在 https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state

目前我想到的方式，还只是利用样式去覆盖，比如这样:

```scss
.btn {
   .a{}
   .b{}
}
// hover-class
.btn.btn-hover {
   .a{}
   .b{}
}
```

这种方式虽然可以达到目的，但是没法和 `tailwindcss` 形成良好的配合，假如你有其他的方式，欢迎补充😄

**Comment by hogking** [comment]
了解了，感谢解答！
