### ISSUE TITLE
为什么例子中view和div混用， 如果我都用div可以编译h5和小程序应该没啥问题吧？

### ISSUE THREAD

**Issue by hackeryutu** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#15]
<img width="844" alt="image" src="https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/assets/16240260/60f4cc3d-d464-45bf-8561-685d308cf231">

**Comment by sonofmagic** [comment]
是的，可以混用的原因，是因为 uni-app 自动把 div 标签，和它对应的css选择器，全部都转义成 view 了，其实写 div 也是可以的，但是你要注意最后也是变成 view。

**Comment by wangh-c** [comment]
所以相对规范的写法应该是 uniapp 尽量使用 uni-app 组件，统一写法，避免混用。这样也会减少 uniapp 的转义

**Comment by hackeryutu** [comment]
好的谢谢
