### ISSUE TITLE
请问这个uniapp vue3 setup ts 如何引入高德小程序插件amap-wx.js ？

### ISSUE THREAD

**Issue by dmskys** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#2]
请问这个uniapp vue3 setup ts 如何引入高德小程序插件amap-wx.js ？大佬请教下
想在小程序实现高德地图选择周边地理位置功能。
https://lbs.amap.com/api/wx/guide/get-data/get-inputtips

**Comment by sonofmagic** [comment]
vue3 steup 语法，你可以和 <script></script> 混写的，当然你直接在 ` setup` 里面引入也没有问题的，待会我下班写个demo吧，你等等哈。

**Comment by dmskys** [comment]
谢谢

**Comment by sonofmagic** [comment]
我写了一个 demo , https://github.com/sonofmagic/uni-app-vue3-for-amap-wx
你只要把key换成你的就可以直接运行，相关的注意点我写在 [README.md](https://github.com/sonofmagic/uni-app-vue3-for-amap-wx#readme) 文档里了
