### ISSUE TITLE
hover-class 下的 dark 模式失效

### ISSUE THREAD

**Issue by RyanLen** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#3]
```html
<view class="bg-gray-100 dark:bg-zinc-800" hover-class="bg-red-500 dark:bg-green-500"></view>
```

编译后
```html
<view class="bg-gray-100 dark_c_bg-zinc-800" hover-class="bg-red-500 dark:bg-green-500"></view>
```

`hover-class` 里的 `dark:bg-green-500` 没有编译

**Comment by sonofmagic** [comment]
这个 issue 我记下了，我会发一个 [weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) 的新版本，来适配黑暗模式，到时候我更新了，来这个issue跟你说一下。

**Comment by sonofmagic** [comment]
[weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) 的 `1.6.6` 版本已经支持去替换 `hover-class` 了。
同时我也把这个模板更新了一下，添加了黑暗模式的支持:
```html
    <view
      class="bg-[#010101] dark:bg-[#fefefe] h-10 w-10"
      hover-class="bg-[#e1e1e1] dark:bg-[#121212]"
    ></view>
```

你的写法已经可以跑通了。

如果可以，欢迎给我的 [weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) 点个 `star` 和 `fork` 感谢支持。

**Comment by sonofmagic** [comment]
https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin/pull/61
