### ISSUE TITLE
[eslint error] in vite.config.ts

### ISSUE THREAD

**Issue by gaokun** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#4]
**描述这个Bug**
vite.config.ts 文件中, eslint报错(用eslint来处理ts error)

Require statement not part of import statement.eslint[@typescript-eslint/no-var-requires](https://typescript-eslint.io/rules/no-var-requires)

**屏幕截图(可选)**
![image](https://user-images.githubusercontent.com/7044628/226334619-caf5934b-a753-4217-b951-06cb2b40d362.png)

其实直接import导入就行了

```ts
import autoprefixer from 'autoprefixer';
import tailwindcss from 'tailwindcss';
import rem2px from 'postcss-rem-to-responsive-pixel';

const postcssPlugins = [autoprefixer(), tailwindcss()];
if (!WeappTailwindcssDisabled) {
  postcssPlugins.push(
    rem2px({
      rootValue: 32,
      propList: ['*'],
      transformUnit: 'rpx',
    }),
  );
}
```

在我这边是可以, 你可以再验证下
Thx

PS: 这个库很不错, 查了很多uniapp集成tailwindcss的方案, 这个库最靠谱

**Comment by sonofmagic** [comment]
是的，直接导入就可以，我文档和这个模板里还是之前老版本的写法直接复制到文档里的，我改一下O(∩_∩)O

**Comment by sonofmagic** [comment]
感谢支持O(∩_∩)O哈哈~

**Comment by gaokun** [comment]
@sonofmagic 还有autoprefixer, tailwindcss这两个, 也需要从commonjs改为esm
