### ISSUE TITLE
运行命令npm run dev:h5:ssr，报错

### ISSUE THREAD

**Issue by 350469960** [sonofmagic/uni-app-vite-vue3-tailwind-vscode-template#7]
运行命令npm run dev:h5:ssr，报错
错误信息如下：
uni --ssr

请注意运行模式下，因日志输出、sourcemap 以及未压缩源码等原因，性能和包体积，均不及发行模式。
正在编译中...
error when starting dev server:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.

运行环境
node: 14.19.3
yarn: 3.4.1

**Comment by sonofmagic** [comment]
嗯，我也复现了，之前从来没有跑过这个命令。
然后我去 uni-app 官网 https://uniapp.dcloud.net.cn/quickstart-cli.html
按照官方文档，创建了新的 Vue3/Vite 项目 (下载的  typescript gitee) 的模板
pnpm 安装之后，也执行了 `pnpm dev:h5:ssr` 结果也报错了。
怀疑这是 uni-app 自己的问题。先持续关注一下这个 ssr issue。

**Comment by sonofmagic** [comment]
我向官方汇报，并创建了一个 issue:
https://github.com/dcloudio/uni-app/issues/4237

**Comment by 350469960** [comment]
这样吗？我试了好多个UI组件库，都报错了，我一直以为是组件库的问题

**Comment by sonofmagic** [comment]
你需求上一定要用 uni-app 做 ssr 吗？ 其实 vue ssr 有更好的选择，就是 nuxt 。

**Comment by 350469960** [comment]
没有，主要是现在做多端应用，在做调研，主要是小程序，想兼容H5-SSR搜索引擎相关的优化
